### PR TITLE
updates first lesson to reflect content of datafiles A1 and A2

### PR DESCRIPTION
**Pull request by hjelmj**
This patch updates the first lesson to reflect the current content of the data folder.
It also updates filenames used in the lesson and all output that is generated using the
commands in the lesson. It also removes a plt.show() which is not necessary with either the
ipython notebook or the qtconsole, so not likely to be used I think, and wasn't included each time when plotting, so I think it is more consistent this way.

One issue I left is whether it is correct to assume that the students / tutor still is working on the A1 data set after the first challenge. It probably should be made explicit which data set we continue with after the first challenge.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Looks good to me. :+1:

**Comment by kynan** [comment]
Yep, I think that's good to go!

**Comment by jrsmith3** [comment]
Oops. [My PR](https://github.com/swcarpentry/python-intermediate-mosquitoes/pull/7) is a partial duplicate of this PR. Is anyone merging these things? Some of the PRs are months old at this point.

**Comment by hjelmj** [comment]
@abostroem @tbekolay - not sure how this works, I presume one of the maintainers will do any merging?

**Comment by tbekolay** [comment]
Sorry yeah, we'll review / merge these. This repo gets a bit neglected as most of the action happens in the [`novice-inflammation`](https://github.com/swcarpentry/python-novice-inflammation) repo, but I'll look at these PRs early next week!

**Comment by jrsmith3** [comment]
@tbekolay Sweet, thanks!

Once this PR gets merged, Issue #6 can be closed as well.

**Comment by tbekolay** [comment]
Thanks @hjelmj, sorry for the delay!

**Comment by hjelmj** [comment]
great, no problem and thanks @tbekolay !

**Pull request merged**
